@WebAPI_HostAddress = http://localhost:5178

GET {{WebAPI_HostAddress}}/notes/+q7jP5gYoOlhvDg7AZhDjQ==/getNotesByTag?tags=Pizza
Accept: application/json
Content-Type: application/json
{
    "Name": "SecondNote",
    "Text": "This is my first note about pizza",
    "Tags": ["Food","Pizza"],
    "SharedKeys": [""]
}

###
